[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["NODE_OPTIONS=--max-old-space-size=4096 pnpm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.js"
