CREATE TABLE `xbot_logistics_briefs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`timeline` json,
	`customsChecklist` json,
	`groundTransportOptions` json,
	`servicePackage` json,
	`hsCodeSuggestion` varchar(20),
	`ataCarnetEligible` boolean,
	`shipByDeadline` timestamp,
	`summaryNotes` text,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `xbot_logistics_briefs_id` PRIMARY KEY(`id`),
	CONSTRAINT `xbot_logistics_briefs_projectId_unique` UNIQUE(`projectId`)
);
--> statement-breakpoint
CREATE TABLE `xbot_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionToken` varchar(128) NOT NULL,
	`userId` int,
	`robotMake` varchar(255),
	`robotModel` varchar(255),
	`robotDimensions` varchar(255),
	`robotWeight` varchar(100),
	`powerRequirements` varchar(255),
	`specialHandling` text,
	`originCountry` varchar(100),
	`originCity` varchar(100),
	`shippingMethod` enum('air','sea','ground'),
	`flightVesselNumber` varchar(100),
	`eta` timestamp,
	`portOfEntry` varchar(255),
	`hsCode` varchar(20),
	`ataCarnet` boolean DEFAULT false,
	`customsBroker` enum('stagegate','own','tbd') DEFAULT 'tbd',
	`customsBrokerName` varchar(255),
	`showId` int,
	`boothNumber` varchar(100),
	`setupDate` timestamp,
	`teardownDate` timestamp,
	`selectedServices` json,
	`groundTransportProvider` enum('stagegate','own','directory'),
	`contacts` json,
	`currentStep` int NOT NULL DEFAULT 1,
	`status` enum('draft','brief_generated','submitted','in_review','confirmed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `xbot_projects_id` PRIMARY KEY(`id`),
	CONSTRAINT `xbot_projects_sessionToken_unique` UNIQUE(`sessionToken`)
);
