/**
 * Bulk-seed StageGate trade_shows from the 2026-2027 Master Conference Calendar.
 * Run: node scripts/seed-shows.js
 * Safe to re-run — skips any show whose name already exists.
 */

const { Client } = require("pg");

const DB =
  "postgresql://postgres.ranqttxqzdrlkqrhgnpy:Legup_labs_2040!@aws-1-us-east-1.pooler.supabase.com:6543/postgres";

// Today = May 17 2026 — anything before this is "past"
function status(startIso) {
  if (!startIso) return "upcoming";
  return new Date(startIso) < new Date("2026-05-17") ? "past" : "upcoming";
}

// fmt: [name, venue, city, startISO, endISO, website, description, roboticsRelevance, estimatedExhibitors]
const SHOWS = [
  // ── 2026 past (kept for history / analytics) ──────────────────────────────
  [
    "CES 2026",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2026-01-06",
    "2026-01-09",
    "https://www.ces.tech/",
    "World's largest consumer & commercial technology show. 148k+ attendees (audited). Highest press-corps density of any event in the calendar. Strong AI/robotics/startup presence.",
    5, 4100,
  ],
  [
    "AAAI-26",
    "Marina Bay Sands",
    "Singapore",
    "2026-01-20",
    "2026-01-27",
    "https://aaai.org/conference/aaai/aaai-26/",
    "Premier broad AI research conference. 5–7k attendees, 10,500+ paper submissions. Academic focus; strong for talent and long-cycle IP discovery.",
    3, null,
  ],
  [
    "ATX West 2026",
    "Anaheim Convention Center",
    "Anaheim",
    "2026-02-03",
    "2026-02-05",
    "https://www.imengineeringwest.com/en/show/show-brands/atx-west.html/",
    "Industrial automation and robotics trade show. 15–20k attendees. Free for qualified professionals.",
    4, null,
  ],
  [
    "Manifest Vegas 2026",
    "The Venetian",
    "Las Vegas",
    "2026-02-09",
    "2026-02-11",
    "https://manife.st",
    "Premier logistics-tech startup networking event. 7k+ attendees including supply-chain C-suite and logistics-tech investors. Hosted Shipper program provides qualified buyer access.",
    4, null,
  ],
  [
    "PACK EXPO East 2026",
    "Pennsylvania Convention Center",
    "Philadelphia",
    "2026-02-17",
    "2026-02-19",
    "https://www.packexpointernational.com",
    "Packaging and processing automation show. 8k est. attendees. Strong for cobot and automation integrators.",
    3, null,
  ],
  [
    "HIMSS26",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2026-03-09",
    "2026-03-12",
    "https://www.himss.org/global-conference",
    "Health IT, AI in healthcare, robotic surgery. 25–28k attendees. Buyer is CIO/CMIO/VP Digital Health, not surgeon.",
    3, 1000,
  ],
  [
    "SXSW 2026",
    "Austin Convention Center",
    "Austin",
    "2026-03-12",
    "2026-03-18",
    "https://sxsw.com/",
    "309k+ attendees across tech, film, music. Innovation/AI track and 40th anniversary edition. High press density; strong for narrative-building and investor access.",
    3, null,
  ],
  [
    "NVIDIA GTC 2026",
    "San Jose McEnery Convention Center",
    "San Jose",
    "2026-03-16",
    "2026-03-19",
    "https://www.nvidia.com/gtc/",
    "30k+ attendees. Physical AI, AI factories, robotics — 1,000+ sessions. Jensen keynote creates multi-week news cycles. Premier content-harvesting event for AI/robotics narrative.",
    5, null,
  ],
  [
    "World Agri-Tech Summit 2026",
    "Marriott Marquis San Francisco",
    "San Francisco",
    "2026-03-17",
    "2026-03-18",
    "https://worldagritechusa.com",
    "Curated 1,700–2k attendee ag-robotics and precision agriculture event. Strong investor program. Co-located with Future Food-Tech.",
    3, null,
  ],
  [
    "LogiMAT 2026",
    "Messe Stuttgart",
    "Stuttgart",
    "2026-03-24",
    "2026-03-26",
    "https://www.logimat-messe.de/",
    "Record 69,856 visitors; 1,671 exhibitors. Europe's top intralogistics and warehouse automation show. AMRs, conveyor systems, picking robots.",
    4, 1671,
  ],
  [
    "SAGES Annual Meeting 2026",
    "Tampa Convention Center",
    "Tampa",
    "2026-03-25",
    "2026-03-28",
    "https://www.sages2026.org/",
    "4–6k attendees; minimally invasive and robotic surgery KOLs. Critical for surgical robotics clinical advisory board recruitment.",
    3, null,
  ],
  [
    "MODEX 2026",
    "Georgia World Congress Center",
    "Atlanta",
    "2026-04-13",
    "2026-04-16",
    "https://www.modexshow.com",
    "Biennial MHI show. 50–60k buyers with $70B collective purchasing power. Free admission. Premier warehouse robotics and AMR buyer event in North America.",
    4, 1000,
  ],
  [
    "Sea-Air-Space 2026",
    "Gaylord National Resort",
    "National Harbor",
    "2026-04-19",
    "2026-04-22",
    "https://seaairspace.org/",
    "Navy League annual event. 15k+ attendees. Naval/maritime warfare, unmanned maritime systems. Free for military/gov't.",
    3, null,
  ],
  [
    "Hannover Messe 2026",
    "Hannover Messe",
    "Hannover",
    "2026-04-20",
    "2026-04-24",
    "https://www.hannovermesse.de/en/",
    "World's largest industrial trade fair. 110k actual attendees, ~3,000 exhibitors. Industrial AI, automation, energy, supply chain. Premier content-harvesting venue for industrial AI narratives.",
    5, 3000,
  ],
  [
    "ISMR 2026",
    "University of Tennessee",
    "Knoxville",
    "2026-04-22",
    "2026-04-24",
    "https://ismr.gatech.edu",
    "International Symposium on Medical Robotics. 300–600 academic attendees. Surgical robotics, image-guided systems. Tier C for commercial lead-gen; high value for clinical partnerships.",
    3, null,
  ],
  [
    "ICLR 2026",
    "Riocentro Convention Center",
    "Rio de Janeiro",
    "2026-04-23",
    "2026-04-27",
    "https://iclr.cc",
    "Deep learning, foundation models, representation learning. 11–13k attendees. Academic; strong for talent discovery and long-range IP scouting.",
    3, null,
  ],
  [
    "Modern Day Marine 2026",
    "Walter E. Washington Convention Center",
    "Washington",
    "2026-04-28",
    "2026-04-30",
    "https://marinemilitaryexpos.com",
    "USMC modernization showcase. 10–15k attendees. Ground robotics, expeditionary logistics, autonomous logistics systems. Free for military/gov't.",
    3, null,
  ],
  [
    "AUVSI XPONENTIAL 2026",
    "Huntington Place Convention Center",
    "Detroit",
    "2026-05-11",
    "2026-05-14",
    "https://www.auvsi.org/event/xponential-2026/",
    "10k+ attendees. Drones/UAS, autonomous vehicles, defense autonomy. Straddles commercial and defense markets. Startup pods from $2,950.",
    5, null,
  ],
  [
    "Web Summit Vancouver 2026",
    "Vancouver Convention Centre",
    "Vancouver",
    "2026-05-11",
    "2026-05-14",
    "https://vancouver.websummit.com/",
    "40k+ attendees. AI, fintech, health tech; 2,000+ startups. ALPHA/BETA startup programs. Strong investor and international press presence.",
    4, null,
  ],
  // ── 2026 upcoming ─────────────────────────────────────────────────────────
  [
    "Home Delivery World USA 2026",
    "Music City Center",
    "Nashville",
    "2026-05-20",
    "2026-05-21",
    "https://www.terrapinn.com/conference/home-delivery-world/index.stm",
    "Last-mile delivery, e-commerce robotics. 3–5k attendees. 75+ startup exhibitors. Key for last-mile automation and delivery robot companies.",
    3, null,
  ],
  [
    "Robotics Summit & Expo 2026",
    "Boston Convention & Exhibition Center",
    "Boston",
    "2026-05-27",
    "2026-05-28",
    "https://www.roboticssummit.com",
    "3–4k attendees. AMRs, humanoids, healthcare/logistics robotics. Expo-Only $125. Strong VC foot traffic (MassRobotics adjacent). RBR50 Gala generates earned media.",
    5, 150,
  ],
  [
    "ICRA 2026",
    "Austria Center Vienna",
    "Vienna",
    "2026-06-01",
    "2026-06-05",
    "https://2026.ieee-icra.org",
    "IEEE flagship robotics conference. 7–8k attendees. Academic robotics & automation research. Tier C for commercial lead-gen; premier for talent and research partnerships.",
    4, null,
  ],
  [
    "AI Summit London 2026",
    "ExCeL London",
    "London",
    "2026-06-10",
    "2026-06-11",
    "https://london.theaisummit.com",
    "10th annual enterprise AI event. 5k+ attendees. Campus/Expo pass from £149. Strong European enterprise AI buyer press coverage.",
    4, null,
  ],
  [
    "Eurosatory 2026",
    "Paris Nord Villepinte",
    "Paris",
    "2026-06-15",
    "2026-06-19",
    "https://www.eurosatory.com/en/home/",
    "Biennial premier European defense show. 57–76k attendees, 2,100–2,400 exhibitors from 150+ countries. Ground robotics, UAVs, C4ISR. Next edition 2028.",
    4, 2400,
  ],
  [
    "Automate 2026",
    "McCormick Place",
    "Chicago",
    "2026-06-22",
    "2026-06-25",
    "https://www.automateshow.com",
    "North America's largest robotics & automation show. 50k+ registrants, 1,000+ exhibitors, FREE show floor. Innovation Pavilion for startups. Premier event for industrial robotics buyers.",
    5, 1000,
  ],
  [
    "RoboCup 2026",
    "Songdo ConvensiA",
    "Incheon",
    "2026-06-30",
    "2026-07-06",
    "https://2026.robocup.org",
    "International robotics competition. 3k competitors, 15k visitors. Research/education focus. Strong for academic partnerships and talent pipeline.",
    4, null,
  ],
  [
    "Manufacturing World Tokyo 2026",
    "Tokyo Big Sight",
    "Tokyo",
    "2026-07-01",
    "2026-07-03",
    "https://www.manufacturing-world.jp/tokyo/en-gb/about.html",
    "70k+ attendees. Smart manufacturing, factory DX, components. Free pre-registration. Key event for Japan manufacturing and robotics market access.",
    4, null,
  ],
  [
    "ICML 2026",
    "COEX Convention Center",
    "Seoul",
    "2026-07-06",
    "2026-07-10",
    "https://icml.cc",
    "Academic ML research. 9–11k attendees. Generative models, optimization, reinforcement learning. Tier C for commercial lead-gen; strong for ML talent discovery.",
    3, null,
  ],
  [
    "RSS 2026",
    "International Convention Centre Sydney",
    "Sydney",
    "2026-07-13",
    "2026-07-17",
    "https://roboticsconference.org",
    "Highly selective foundational robotics research conference. 1–1.5k attendees. Tier C for commercial lead-gen; top-tier for foundational robotics research relationships.",
    4, null,
  ],
  [
    "VB Transform 2026",
    "Computer History Museum",
    "Menlo Park",
    "2026-07-14",
    "2026-07-15",
    "https://venturebeat.com/vbtransform2026",
    "600+ enterprise AI practitioners. Agentic AI and LLMOps focus. High signal-to-noise ratio for enterprise AI narrative building.",
    3, null,
  ],
  [
    "WAIC Shanghai 2026",
    "World Expo Exhibition & Convention Center",
    "Shanghai",
    "2026-07-22",
    "2026-07-24",
    "https://en.wikipedia.org/wiki/World_Artificial_Intelligence_Conference",
    "350k+ attendees. National AI strategy, humanoid robotics, smart manufacturing. Government-organized; strong for China market intelligence.",
    4, null,
  ],
  [
    "World Robot Conference 2026",
    "China National Convention Center",
    "Beijing",
    "2026-08-08",
    "2026-08-12",
    "https://www.worldrobotconference.com/en/",
    "200k+ visitors. Full-spectrum robotics: humanoids, industrial, medical, service. Key event for China robotics ecosystem access and APAC commercial intelligence.",
    5, null,
  ],
  [
    "PARCEL Forum 2026",
    "Orange County Convention Center",
    "Orlando",
    "2026-09-14",
    "2026-09-16",
    "https://ecommercetech.io/events/parcel-forum",
    "1.5–2.5k attendees. Small-package supply chain, last-mile automation and carrier management. Niche but high relevance for last-mile robotics.",
    3, null,
  ],
  [
    "IMTS 2026",
    "McCormick Place",
    "Chicago",
    "2026-09-14",
    "2026-09-19",
    "https://www.imts.com",
    "Biennial. 86k+ expected; 1.2M sq ft of exhibits. Largest manufacturing tech show in Western Hemisphere. CNC, additive mfg, robotics, precision machining. Next edition 2028.",
    5, 1800,
  ],
  [
    "IROS 2026",
    "David L. Lawrence Convention Center",
    "Pittsburgh",
    "2026-09-27",
    "2026-10-01",
    "https://2026.ieee-iros.org/",
    "Intelligent robots, autonomous vehicles, manipulation. 3–5k attendees. Academic but with strong industry participation. Key for robotics research partnerships.",
    4, null,
  ],
  [
    "AUSA Annual Meeting 2026",
    "Walter E. Washington Convention Center",
    "Washington",
    "2026-10-12",
    "2026-10-14",
    "https://meetings.ausa.org/annual/2026/",
    "33–44k attendees, 700+ exhibitors. U.S. Army modernization, defense tech, robotics/UAS. Free registration. Ground robotics and logistics autonomy primary focus.",
    4, 700,
  ],
  [
    "CIIF 2026",
    "National Exhibition and Convention Center",
    "Shanghai",
    "2026-10-12",
    "2026-10-16",
    "https://bcic-brics.org/events/715",
    "224k+ professional visitors. CNC, industrial automation, robotics sub-show. Free pre-registration. Gateway to Chinese manufacturing procurement.",
    4, null,
  ],
  [
    "PACK EXPO International 2026",
    "McCormick Place",
    "Chicago",
    "2026-10-18",
    "2026-10-21",
    "https://www.packexpointernational.com",
    "48k+ attendees. Packaging machinery, automation, robotics for packaging lines. $30 early/$130 late registration.",
    3, null,
  ],
  [
    "RoboBusiness 2026",
    "Santa Clara Convention Center",
    "Santa Clara",
    "2026-10-19",
    "2026-10-21",
    "https://www.robobusiness.com",
    "2–2.5k attendees, 150+ exhibitors. Tightest signal-to-noise ratio in commercial robotics. RBR50 Innovators awards drives earned media. Premier startup robotics event.",
    5, 150,
  ],
  [
    "FIRA USA 2026",
    "Yakima Convention Center",
    "Yakima",
    "2026-10-20",
    "2026-10-22",
    "https://fira-usa.com",
    "500–1.5k attendees. Agricultural robotics, harvest automation, specialty crops. Free for farmers and journalists. High relevance concentration for ag-robotics.",
    3, null,
  ],
  [
    "FABTECH 2026",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2026-10-21",
    "2026-10-23",
    "https://www.fabtechexpo.com/",
    "31k+ attendees. Metal forming, fabricating, welding, cutting automation. Free advance registration. Key for welding robots and metalworking automation.",
    4, null,
  ],
  [
    "ITAP 2026",
    "Marina Bay Sands Expo",
    "Singapore",
    "2026-10-21",
    "2026-10-23",
    "https://www.industrial-transformation.com",
    "16–20k attendees. Industry 4.0, smart manufacturing, APAC digital transformation. Free for qualified industry professionals.",
    4, null,
  ],
  [
    "Assembly Show 2026",
    "Donald E. Stephens Convention Center",
    "Rosemont",
    "2026-10-27",
    "2026-10-29",
    "https://www.assemblymag.com/the-assembly-show",
    "5–8k attendees. Assembly automation, robotics, quality inspection. Free for qualified buyers.",
    3, null,
  ],
  [
    "CoRL 2026",
    "Austin Convention Center",
    "Austin",
    "2026-11-09",
    "2026-11-12",
    "https://www.corl.org",
    "800–1.2k attendees. Robot learning, imitation/reinforcement learning. Academic but with strong commercial-translation relevance for AI-first robotics companies.",
    4, null,
  ],
  [
    "Web Summit Lisbon 2026",
    "Altice Arena",
    "Lisbon",
    "2026-11-09",
    "2026-11-12",
    "https://websummit.com/web-summit-2026/",
    "70k+ attendees from 160+ countries. 1,500+ investors. ALPHA (pre-Series A) and BETA startup programs. Premier international tech event; strong European press coverage.",
    4, null,
  ],
  [
    "MEDICA 2026",
    "Messe Düsseldorf",
    "Düsseldorf",
    "2026-11-16",
    "2026-11-19",
    "https://www.medica.de",
    "World's largest medical device trade show. 83k+ visitors, 5k+ exhibitors. Medical devices, robotic surgery, digital health. Essential for European healthcare robotics market access.",
    3, 5000,
  ],
  [
    "SPS Nuremberg 2026",
    "Messe Nürnberg",
    "Nuremberg",
    "2026-11-24",
    "2026-11-26",
    "https://sps.mesago.com/nuernberg/en.html",
    "56k+ attendees. Smart automation, drive tech, IIoT/Industry 4.0. European counterpart to Automate for controls and drive technology. Strong German industrial buyer base.",
    4, null,
  ],
  [
    "RSNA 2026",
    "McCormick Place",
    "Chicago",
    "2026-11-29",
    "2026-12-03",
    "https://www.rsna.org/annual-meeting",
    "54k+ attendees. Radiology, medical imaging AI, image-guided robotics. Premier venue for imaging AI/surgical navigation launches. Strong radiologist and med-tech press coverage.",
    3, null,
  ],
  [
    "Humanoids 2026",
    "Santa Clara Convention Center",
    "Santa Clara",
    "2026-12-06",
    "2026-12-09",
    "https://www.massrobotics.org/event/2026-ieee-ras-25th-international-conference-on-humanoid-robots/",
    "25th Anniversary IEEE-RAS Humanoids conference. 500–1k attendees. Densest concentration of humanoid-focused engineers, investors, and journalists of any show this calendar.",
    5, null,
  ],
  [
    "NeurIPS 2026",
    "International Convention Centre Sydney",
    "Sydney",
    "2026-12-06",
    "2026-12-12",
    "https://neurips.cc/Conferences/2026/Dates",
    "18–20k attendees. Academic ML/AI research; deep learning, optimization, generative models. Tier C for commercial lead-gen; top-tier for AI research talent pipeline.",
    3, null,
  ],
  [
    "AI Summit New York 2026",
    "Javits Center",
    "New York",
    "2026-12-09",
    "2026-12-10",
    "https://newyork.theaisummit.com",
    "5k+ senior decision-makers from 75 countries. Enterprise AI commercial deployment focus. 539 speakers, 10 content tracks. Strong C-suite buyer and press presence.",
    4, null,
  ],
  // ── 2027 ──────────────────────────────────────────────────────────────────
  [
    "CES 2027",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2027-01-06",
    "2027-01-09",
    "https://www.cta.tech/events/ces-2027/",
    "150k+ attendees est. Consumer tech, AI, robotics. AI interest +22% YoY trend. Highest press-corps density of the annual calendar. Premier content-harvesting event.",
    5, 4200,
  ],
  [
    "IDEX 2027",
    "Abu Dhabi National Exhibition Centre",
    "Abu Dhabi",
    "2027-01-25",
    "2027-01-29",
    "https://www.idexuae.ae",
    "Biennial. 200k+ visitors, 1,565+ exhibitors from 167 countries. Land, sea, air, cyber/unmanned defense. Free pre-registration. Premier Gulf defense procurement event. 70% of 2025 exhibitors already committed.",
    4, 1565,
  ],
  [
    "Manifest Vegas 2027",
    "The Venetian",
    "Las Vegas",
    "2027-02-08",
    "2027-02-10",
    "https://manife.st/register/",
    "7k+ attendees. Supply chain tech, warehouse robotics, AI logistics. Hosted Shipper program. Premier deal-making venue for warehouse robotics and last-mile automation.",
    4, null,
  ],
  [
    "ATX West 2027",
    "Anaheim Convention Center",
    "Anaheim",
    "2027-02-09",
    "2027-02-11",
    "https://www.imengineeringwest.com/",
    "Industrial automation and robotics; co-located IME West. 15–20k attendees. Free for qualified professionals.",
    4, null,
  ],
  [
    "AAAI-27",
    "Palais des congrès de Montréal",
    "Montréal",
    "2027-02-16",
    "2027-02-23",
    "https://aaai.org/conference/aaai/aaai-27/",
    "Broad AI research conference. 5–7k attendees. Academic focus; strong for talent and long-cycle relationship-building.",
    3, null,
  ],
  [
    "Smart Factory Expo Tokyo 2027",
    "Tokyo Big Sight",
    "Tokyo",
    "2027-02-17",
    "2027-02-19",
    "https://www.fiweek.jp/tokyo/en-gb.html",
    "88k+ attendees (FIW total). Smart factory, IoT, robotics, green factory. Free pre-registration. Key for Japan industrial robotics market.",
    4, null,
  ],
  [
    "World Agri-Tech Summit 2027",
    "Marriott Marquis San Francisco",
    "San Francisco",
    "2027-03-09",
    "2027-03-10",
    "https://worldagritechusa.com",
    "1,700–2k attendees. Precision ag, agri-robotics, AI in farming. Strong investor program. Co-located with Future Food-Tech 2027.",
    3, null,
  ],
  [
    "SXSW 2027",
    "Austin Convention Center",
    "Austin",
    "2027-03-15",
    "2027-03-21",
    "https://sxsw.com/",
    "300–320k attendees. Innovation/AI and tech culture tracks. Strong press and investor presence for early-stage narrative building.",
    3, null,
  ],
  [
    "LogiMAT 2027",
    "Messe Stuttgart",
    "Stuttgart",
    "2027-03-16",
    "2027-03-18",
    "https://www.logimat-messe.de/",
    "65–70k attendees est. Intralogistics, warehouse automation, AMRs. Europe's leading annual warehouse automation event.",
    4, null,
  ],
  [
    "NVIDIA GTC 2027",
    "San Jose McEnery Convention Center",
    "San Jose",
    "2027-03-15",
    "2027-03-18",
    "https://www.nvidia.com/gtc/",
    "35k+ attendees est. AI/GPU developer ecosystem, physical AI, robotics. Annual anchor for AI/robotics press tour strategy.",
    5, null,
  ],
  [
    "Sea-Air-Space 2027",
    "Gaylord National Resort",
    "National Harbor",
    "2027-04-04",
    "2027-04-07",
    "https://seaairspace.org/about/",
    "15k+ attendees. Naval/maritime warfare, unmanned maritime systems. Free for military/gov't.",
    3, null,
  ],
  [
    "Hannover Messe 2027",
    "Hannover Messe",
    "Hannover",
    "2027-04-05",
    "2027-04-08",
    "https://www.hannovermesse.de/en/",
    "110–130k attendees. Industrial AI, automation, energy. Partner Country: Spain. Compressed 4-day format. Annual European industrial press-tour anchor.",
    5, 3000,
  ],
  [
    "HIMSS27",
    "McCormick Place",
    "Chicago",
    "2027-04-05",
    "2027-04-08",
    "https://www.himssconference.com/save-the-date-for-himss27/",
    "25–30k attendees. Health IT, digital health, AI, robotic surgery. Buyer is CIO/CMIO/VP Digital Health. Commercial gateway for AI-enabled healthcare platforms.",
    3, 1000,
  ],
  [
    "SAGES Annual Meeting 2027",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2027-04-06",
    "2027-04-09",
    "https://www.sages.org/",
    "4–6k attendees. Minimally invasive and robotic surgery. Las Vegas edition. KOL engagement for surgical robotics companies.",
    3, null,
  ],
  [
    "Transform 2027",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2027-04-12",
    "2027-04-14",
    "https://transform.us/conference/",
    "4,500 attendees. AI + humanity, HR technology, workplace transformation. Informa-produced. Strong C-suite enterprise AI buyer presence.",
    3, null,
  ],
  [
    "Modern Day Marine 2027",
    "Walter E. Washington Convention Center",
    "Washington",
    "2027-04-13",
    "2027-04-15",
    "https://marinemilitaryexpos.com",
    "USMC modernization. 10–15k attendees. Ground robotics, expeditionary logistics, autonomous logistics. Free for military/gov't.",
    3, null,
  ],
  [
    "ProMat 2027",
    "McCormick Place",
    "Chicago",
    "2027-04-19",
    "2027-04-21",
    "https://www.promatshow.com",
    "Biennial MHI show. 50k+ buyers, FREE admission. $70B collective purchasing power. North America's premier logistics/material-handling buyer event.",
    4, 1000,
  ],
  [
    "Automate 2027",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2027-05-10",
    "2027-05-13",
    "https://www.automateshow.com",
    "50k+ attendees est. North America's largest robotics & automation show — moves to Las Vegas. FREE show floor. First Las Vegas edition; early exhibitor position is strategically valuable.",
    5, 1000,
  ],
  [
    "AUVSI XPONENTIAL 2027",
    "Miami Beach Convention Center",
    "Miami Beach",
    "2027-05-17",
    "2027-05-20",
    "https://www.auvsi.org/event/xponential-2027/",
    "10k+ attendees. Drones/UAS, autonomous vehicles, defense autonomy. Moves to Miami Beach. Startup pods accessible from ~$2,950.",
    5, null,
  ],
  [
    "ICRA 2027",
    "COEX Convention Center",
    "Seoul",
    "2027-05-24",
    "2027-05-28",
    "https://2027.ieee-icra.org",
    "IEEE flagship robotics conference. 10k+ attendees est. Academic robotics & automation research. Seoul edition opens Feb 2027.",
    4, null,
  ],
  [
    "Web Summit Vancouver 2027",
    "Vancouver Convention Centre",
    "Vancouver",
    "2027-05-25",
    "2027-05-28",
    "https://vancouver.websummit.com/tickets/attendees/",
    "40–45k attendees. AI, fintech, health tech; 2,000+ startups. ALPHA/BETA programs. $495 early pass. Strong APAC and North American tech press.",
    4, null,
  ],
  [
    "RoboCup 2027",
    "Nuremberg Convention Center",
    "Nuremberg",
    "2027-06-15",
    "2027-06-21",
    "https://www.euinnovationvalley.de/en/news-events/robocup-2027",
    "International robotics competition. European edition. Research/education focus; strong for academic partnerships and humanoid/service robot talent.",
    3, null,
  ],
  [
    "Automatica 2027",
    "Messe München",
    "Munich",
    "2027-06-22",
    "2027-06-25",
    "https://automatica-munich.com/en/trade-fair/",
    "Biennial. 45–50k attendees. Smart automation, industrial robotics, machine vision, AI. Co-located with World of Photonics Munich 2027. Next edition 2029.",
    5, null,
  ],
  [
    "AI Summit London 2027",
    "ExCeL London",
    "London",
    "2027-06-08",
    "2027-06-09",
    "https://london.theaisummit.com",
    "5.5–6k attendees est. Enterprise AI deployment. Strong European press and enterprise buyer presence.",
    4, null,
  ],
  [
    "Ai4 Conference 2027",
    "The Venetian",
    "Las Vegas",
    "2027-08-03",
    "2027-08-05",
    "https://ai4.io/",
    "10–12k attendees est. Enterprise AI, agentic AI. Follow-on to AI4 2026. Growing enterprise AI adoption focus.",
    4, null,
  ],
  [
    "World Robot Conference 2027",
    "China National Convention Center",
    "Beijing",
    "2027-08-05",
    "2027-08-09",
    "https://www.worldrobotconference.com/en/",
    "200k+ visitors est. Full-spectrum robotics: humanoids, industrial, medical, service. Exhibition generally free. Key for China robotics ecosystem.",
    5, null,
  ],
  [
    "DSEI 2027",
    "ExCeL London",
    "London",
    "2027-09-07",
    "2027-09-10",
    "https://www.dsei.co.uk",
    "Biennial. 40–60k attendees, 1,600+ exhibitors from 62 countries. Largest combined defense show in Europe. SME Springboard scheme for emerging companies. Security clearance required.",
    4, 1600,
  ],
  [
    "FABTECH 2027",
    "McCormick Place",
    "Chicago",
    "2027-09-13",
    "2027-09-16",
    "https://www.fabtechexpo.com/",
    "38–42k attendees. Chicago edition historically larger than Las Vegas. Metal forming, fabricating, welding automation. Free advance registration.",
    4, null,
  ],
  [
    "SPS Americas 2027",
    "Georgia World Congress Center",
    "Atlanta",
    "2027-09-14",
    "2027-09-16",
    "https://sps-americas.us.messefrankfurt.com/usa/en/attend/attendee-information.html",
    "Debut standalone North American SPS smart automation event. New event to monitor as it establishes its audience.",
    3, null,
  ],
  [
    "PACK EXPO Las Vegas 2027",
    "Las Vegas Convention Center",
    "Las Vegas",
    "2027-09-27",
    "2027-09-29",
    "https://www.packexpolasvegas.com/the-show",
    "30–35k attendees. Packaging, processing automation. Las Vegas biennial edition.",
    3, null,
  ],
  [
    "EMO Milan 2027",
    "Fiera Milano",
    "Milan",
    "2027-10-04",
    "2027-10-08",
    "https://www.emo-milan.com",
    "Biennial. 150k+ visitors. World's leading machine tools and production technology show. CNC automation, robotics for manufacturing, precision production. Next edition 2029.",
    4, null,
  ],
  [
    "AUSA Annual Meeting 2027",
    "Walter E. Washington Convention Center",
    "Washington",
    "2027-10-11",
    "2027-10-13",
    "https://www.ausa.org/future-annual-meeting-dates",
    "33–44k attendees, 700+ exhibitors. U.S. Army modernization. Ground robotics and logistics autonomy primary focus. Free registration.",
    4, 700,
  ],
  [
    "ITAP 2027",
    "Marina Bay Sands Expo",
    "Singapore",
    "2027-10-20",
    "2027-10-22",
    "https://www.industrial-transformation.com",
    "16–20k attendees est. Industry 4.0, smart manufacturing, APAC digital transformation. Free for qualified industry professionals.",
    4, null,
  ],
  [
    "FIRA USA 2027",
    "TBA",
    "Pacific NW/CA",
    "2027-10-20",
    "2027-10-22",
    "https://world-fira.com",
    "Agricultural robotics, harvest automation. 500–1.5k attendees. High relevance concentration for ag-robotics.",
    3, null,
  ],
  [
    "IROS 2027",
    "Fortezza da Basso",
    "Florence",
    "2027-10-01",
    "2027-10-05",
    "https://en.wikipedia.org/wiki/International_Conference_on_Intelligent_Robots_and_Systems",
    "Intelligent robots, autonomous vehicles, manipulation. 3–5k attendees. Florence edition.",
    4, null,
  ],
  [
    "Assembly Show 2027",
    "Donald E. Stephens Convention Center",
    "Rosemont",
    "2027-10-26",
    "2027-10-28",
    "https://www.assemblymag.com/the-assembly-show/exhibitor-info",
    "5–8k attendees. Assembly automation, robotics, quality. Free for qualified buyers.",
    3, null,
  ],
  [
    "Agritechnica 2027",
    "Hannover Messe",
    "Hannover",
    "2027-11-14",
    "2027-11-20",
    "https://www.agritechnica.com/",
    "Biennial. 476k+ visitors, 2,819 exhibitors from 171 countries. World's largest agricultural machinery show. Autonomous tractors, field robotics, precision farming. Next edition 2029.",
    4, 2819,
  ],
  [
    "RSNA 2027",
    "McCormick Place",
    "Chicago",
    "2027-11-14",
    "2027-11-18",
    "https://www.rsna.org/annual-meeting/future-and-past-meetings",
    "54k+ attendees. Radiology, medical imaging AI, image-guided robotics. Annual anchor for imaging AI and surgical navigation market.",
    3, null,
  ],
  [
    "SPS Nuremberg 2027",
    "Messe Nürnberg",
    "Nuremberg",
    "2027-11-23",
    "2027-11-25",
    "https://sps.mesago.com/nuernberg/en.html",
    "56k+ attendees est. Smart automation, IIoT, Industry 4.0. European counterpart to Automate for industrial controls buyers.",
    4, null,
  ],
  [
    "MEDICA 2027",
    "Messe Düsseldorf",
    "Düsseldorf",
    "2027-11-15",
    "2027-11-18",
    "https://www.medica.de",
    "83k+ visitors est. World's largest medical device show. Medical devices, robotic surgery, digital health. Essential for European healthcare robotics.",
    3, 5000,
  ],
  [
    "Web Summit Lisbon 2027",
    "Altice Arena",
    "Lisbon",
    "2027-11-08",
    "2027-11-11",
    "https://websummit.com/",
    "72k+ attendees est. Broad tech + AI. ALPHA/BETA startup programs. Premier international tech event; strong European press.",
    4, null,
  ],
  [
    "AI Summit New York 2027",
    "Javits Center",
    "New York",
    "2027-12-08",
    "2027-12-09",
    "https://newyork.theaisummit.com",
    "5.5–6k senior decision-makers est. Enterprise AI. Strong C-suite buyer and press presence.",
    4, null,
  ],
  [
    "iREX 2027",
    "Tokyo Big Sight",
    "Tokyo",
    "2027-12-02",
    "2027-12-05",
    "https://www.eventseye.com/fairs/f-irex-20846-1.html",
    "Biennial. World's largest robot-dedicated show. 140k+ visitors, FREE entry. Premier window into Japanese industrial robotics supply chain and APAC automation market. Next edition 2029.",
    5, null,
  ],
  [
    "RoboBusiness 2027",
    "Santa Clara Convention Center",
    "Santa Clara",
    "2027-10-19",
    "2027-10-21",
    "https://www.robobusiness.com",
    "2–2.5k attendees, 150+ exhibitors est. Commercial robotics. RBR50 awards drives trade press earned media. Annual commercial robotics signal event.",
    5, 150,
  ],
  [
    "Robotics Summit & Expo 2027",
    "Boston Convention & Exhibition Center",
    "Boston",
    "2027-05-25",
    "2027-05-26",
    "https://www.roboticssummit.com",
    "3–4k attendees. AMRs, humanoids, healthcare/logistics robotics. Strong VC foot traffic. RBR50 Gala. Annual Boston robotics market touchpoint.",
    5, 150,
  ],
  [
    "Humanoids 2027",
    "TBA",
    "TBA",
    "2027-12-08",
    "2027-12-11",
    "https://www.showsbee.com/fairs/105038-IEEE-Humanoids-2027.html",
    "26th IEEE-RAS Humanoids conference. 500–1k attendees. Bipedal locomotion, humanoid robotics, HRI. Dates TBA.",
    5, null,
  ],
  [
    "CoRL 2027",
    "TBA",
    "TBA",
    "2027-11-09",
    "2027-11-12",
    "https://www.robot-learning.org",
    "Robot learning, imitation/reinforcement learning. 800–1.2k attendees. Dates TBA.",
    4, null,
  ],
  [
    "CIIF 2027",
    "National Exhibition and Convention Center",
    "Shanghai",
    "2027-10-12",
    "2027-10-16",
    "https://www.showsbee.com/fairs/79739-China-International-Industry-Fair-2027.html",
    "200–230k+ visitors est. CNC, industrial automation, robotics. Free pre-registration. Key for Chinese manufacturing procurement.",
    4, null,
  ],
];

async function main() {
  const client = new Client({ connectionString: DB });
  await client.connect();
  console.log(`Connected. Seeding ${SHOWS.length} shows...\n`);

  let inserted = 0, skipped = 0, errors = 0;

  for (const [name, venue, city, startDate, endDate, website, description, roboticsRelevance, estimatedExhibitors] of SHOWS) {
    try {
      const exists = await client.query('SELECT id FROM trade_shows WHERE name = $1', [name]);
      if (exists.rows.length > 0) {
        console.log(`  ~ skip  [${exists.rows[0].id}] ${name}`);
        skipped++;
        continue;
      }

      const s = status(startDate);
      const result = await client.query(
        `INSERT INTO trade_shows
           (name, venue, city, "startDate", "endDate", website, description, status, "roboticsRelevance", "estimatedExhibitors")
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
         RETURNING id`,
        [name, venue, city, startDate, endDate, website, description, s, roboticsRelevance, estimatedExhibitors]
      );
      console.log(`  ✓ ${s === 'past' ? 'past' : 'new '} [${result.rows[0].id}] ${name}`);
      inserted++;
    } catch (e) {
      console.error(`  ✗ ERROR ${name}: ${e.message}`);
      errors++;
    }
  }

  await client.end();
  console.log(`\nDone — ${inserted} inserted, ${skipped} already existed, ${errors} errors`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });
